/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.JScrollPane;
/**
 *
 * @author amol
 */
public class PatronDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form Details
     */
    ArrayList<BillDetails> billList;
      ArrayList<RoomDetails> roomList;
          ArrayList<CameraDetails> cameraList;
      int rid;
    
    public PatronDetailsFrame() throws  UnsupportedEncodingException {
        initComponents();
        System.out.println(PatronDetails.pid);
        System.out.println(PatronDetails.type);
        
        if(PatronDetails.type.equalsIgnoreCase("student"))
        {
            studentPanel.setVisible(true);
            facultyPanel.setVisible(false);
            confRoomRadioButton.setVisible(false);
            
            DatabaseHelper.getStudentDetails(PatronDetails.pid);
            //DatabaseHelper.getStudentDetails();
            displayStudentDetails();
            
        }
        else if(PatronDetails.type.equalsIgnoreCase("faculty"))
        {
            studentPanel.setVisible(false);
            facultyPanel.setVisible(true);
            
            DatabaseHelper.getFacultyDetails(PatronDetails.pid);
            //DatabaseHelper.getStudentDetails();
            displayFacultyDetails();
        }
        
        // call DatabaseHelper.getPatronDetails();
        // 
        
    }

       private void populateBillList() throws SQLException {
        
        DefaultListModel dlm = new DefaultListModel();
        
        billList =  DatabaseHelper.getBill();
        //dlm.addElement("Resource    :    Resource ID     :    Amount ");
        for(int i=0; i< billList.size(); i++)
        {
            BillDetails bill = billList.get(i);
            dlm.addElement(bill.resourceType+"     :    "+bill.rid+"     :    "+bill.amount);
            jListAllBill.setModel(dlm);
          
        }
       }
        
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        publicationButtonGroup = new javax.swing.ButtonGroup();
        roomButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        profilePanel = new javax.swing.JPanel();
        facultyPanel = new javax.swing.JPanel();
        fNumberLabel = new javax.swing.JLabel();
        fFnameLabel = new javax.swing.JLabel();
        fLnameLabel = new javax.swing.JLabel();
        fDeptLabel = new javax.swing.JLabel();
        fNationalityLabel = new javax.swing.JLabel();
        fCtegoryLabel = new javax.swing.JLabel();
        fNumberTxtField = new javax.swing.JTextField();
        fFnameTxtField = new javax.swing.JTextField();
        fLnameTxtField = new javax.swing.JTextField();
        fDeptTxtField = new javax.swing.JTextField();
        fNationalityTxtField = new javax.swing.JTextField();
        fCategoryTxtField = new javax.swing.JTextField();
        saveChangesBtnFaculty = new javax.swing.JButton();
        studentPanel = new javax.swing.JPanel();
        studentIdLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        nationalityLabel = new javax.swing.JLabel();
        phoneNoLabel = new javax.swing.JLabel();
        altPhoneNoLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        classificationLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        degProgLabel = new javax.swing.JLabel();
        sidTxtField = new javax.swing.JTextField();
        fnameTxtField = new javax.swing.JTextField();
        lnameTxtField = new javax.swing.JTextField();
        sextxtField = new javax.swing.JTextField();
        nationalityTxtField = new javax.swing.JTextField();
        phoneNoTxtField = new javax.swing.JTextField();
        altphoneNoTxtField = new javax.swing.JTextField();
        dobTxtField = new javax.swing.JTextField();
        deptTxtField = new javax.swing.JTextField();
        classificationTxtField = new javax.swing.JTextField();
        categTxtField = new javax.swing.JTextField();
        degprogTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxtField = new javax.swing.JTextArea();
        saveChangesBtnStudent = new javax.swing.JButton();
        checkedOutResourcesPanel = new javax.swing.JPanel();
        checkedOutPubLabel = new javax.swing.JLabel();
        checkedOutBookButton = new javax.swing.JRadioButton();
        checkedOutJournalButton = new javax.swing.JRadioButton();
        checkedOutConfButton = new javax.swing.JRadioButton();
        checkoutRoomLabel = new javax.swing.JLabel();
        checkedoutStudyButton = new javax.swing.JRadioButton();
        checkedOutConfRoom = new javax.swing.JRadioButton();
        checkedOutCameraButton = new javax.swing.JRadioButton();
        resReqPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollRequestPublication = new javax.swing.JScrollPane();
        roomCheckoutButton = new javax.swing.JButton();
        cameraCheckoutButton = new javax.swing.JButton();
        requestResourceList = new javax.swing.JScrollPane();
        jListRequestRoom = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jRequestResourceCamera = new javax.swing.JList();
        notifPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneReminder = new javax.swing.JScrollPane();
        balancePanel = new javax.swing.JPanel();
        balanceDueLabel = new javax.swing.JLabel();
        amountDueTxtField = new javax.swing.JTextField();
        clearBalanceButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAllBill = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        publicationPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bookRadioButton = new javax.swing.JRadioButton();
        publicationLabel = new javax.swing.JLabel();
        journalRadioButton = new javax.swing.JRadioButton();
        confRadioButton = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        cameraLabel = new javax.swing.JLabel();
        cameraSearchButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        roomLabel = new javax.swing.JLabel();
        studyRoomRadioButton = new javax.swing.JRadioButton();
        confRoomRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        profilePanel.setPreferredSize(new java.awt.Dimension(838, 370));

        fNumberLabel.setText("Faculty number");

        fFnameLabel.setText("First name");

        fLnameLabel.setText("Last name");

        fDeptLabel.setText("Department");

        fNationalityLabel.setText("Nationality");

        fCtegoryLabel.setText("Category");

        fNumberTxtField.setEditable(false);

        saveChangesBtnFaculty.setText("SaveChanges");
        saveChangesBtnFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesBtnFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout facultyPanelLayout = new javax.swing.GroupLayout(facultyPanel);
        facultyPanel.setLayout(facultyPanelLayout);
        facultyPanelLayout.setHorizontalGroup(
            facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPanelLayout.createSequentialGroup()
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fNumberLabel)
                                .addComponent(fFnameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fLnameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fDeptLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(fNationalityLabel)
                            .addComponent(fCtegoryLabel))
                        .addGap(41, 41, 41)
                        .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fCategoryTxtField)
                            .addComponent(fFnameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(fNumberTxtField)
                            .addComponent(fLnameTxtField)
                            .addComponent(fDeptTxtField)
                            .addComponent(fNationalityTxtField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveChangesBtnFaculty)))
                .addContainerGap())
        );
        facultyPanelLayout.setVerticalGroup(
            facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNumberLabel)
                    .addComponent(fNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fFnameLabel)
                    .addComponent(fFnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fLnameLabel)
                    .addComponent(fLnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fDeptLabel)
                    .addComponent(fDeptTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNationalityLabel)
                    .addComponent(fNationalityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fCtegoryLabel)
                    .addComponent(fCategoryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(saveChangesBtnFaculty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentIdLabel.setText("Student id");

        fnameLabel.setText("First name");

        lnameLabel.setText("Last name");

        sexLabel.setText("Sex");

        nationalityLabel.setText("Nationality");

        phoneNoLabel.setText("Phone number");

        altPhoneNoLabel.setText("Alternate phone number");

        addressLabel.setText("Address");

        dobLabel.setText("Date of birth");

        deptLabel.setText("Department");

        classificationLabel.setText("Classification");

        categoryLabel.setText("Category");

        degProgLabel.setText("Degree program");

        sidTxtField.setEditable(false);

        jScrollPane1.setHorizontalScrollBar(null);

        addressTxtField.setColumns(20);
        addressTxtField.setLineWrap(true);
        addressTxtField.setRows(5);
        jScrollPane1.setViewportView(addressTxtField);

        saveChangesBtnStudent.setText("Save Changes");
        saveChangesBtnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesBtnStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentIdLabel)
                    .addComponent(degProgLabel)
                    .addComponent(categoryLabel)
                    .addComponent(classificationLabel)
                    .addComponent(deptLabel)
                    .addComponent(dobLabel)
                    .addComponent(addressLabel)
                    .addComponent(altPhoneNoLabel)
                    .addComponent(phoneNoLabel)
                    .addComponent(nationalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexLabel)
                    .addComponent(lnameLabel)
                    .addComponent(fnameLabel))
                .addGap(73, 73, 73)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveChangesBtnStudent)
                    .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fnameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(lnameTxtField)
                        .addComponent(sextxtField)
                        .addComponent(dobTxtField)
                        .addComponent(deptTxtField)
                        .addComponent(categTxtField)
                        .addComponent(degprogTxtField)
                        .addComponent(sidTxtField)
                        .addComponent(nationalityTxtField)
                        .addComponent(phoneNoTxtField)
                        .addComponent(altphoneNoTxtField)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(classificationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdLabel)
                    .addComponent(sidTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnameLabel)
                    .addComponent(fnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lnameLabel)
                    .addComponent(lnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sexLabel)
                    .addComponent(sextxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationalityLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nationalityTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneNoLabel)
                    .addComponent(phoneNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(altPhoneNoLabel)
                    .addComponent(altphoneNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(addressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classificationLabel)
                    .addComponent(classificationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degprogTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degProgLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveChangesBtnStudent)
                .addContainerGap())
        );

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(facultyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facultyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(studentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Profile", profilePanel);

        checkedOutPubLabel.setText("Publication");

        buttonGroup1.add(checkedOutBookButton);
        checkedOutBookButton.setText("Book");
        checkedOutBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedOutBookButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkedOutJournalButton);
        checkedOutJournalButton.setText("Journal");
        checkedOutJournalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedOutJournalButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkedOutConfButton);
        checkedOutConfButton.setText("Conference proceeding");
        checkedOutConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedOutConfButtonActionPerformed(evt);
            }
        });

        checkoutRoomLabel.setText("Room");

        buttonGroup2.add(checkedoutStudyButton);
        checkedoutStudyButton.setText("Study room");
        checkedoutStudyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedoutStudyButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(checkedOutConfRoom);
        checkedOutConfRoom.setText("Conference room");
        checkedOutConfRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedOutConfRoomActionPerformed(evt);
            }
        });

        checkedOutCameraButton.setText("Camera");
        checkedOutCameraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedOutCameraButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkedOutResourcesPanelLayout = new javax.swing.GroupLayout(checkedOutResourcesPanel);
        checkedOutResourcesPanel.setLayout(checkedOutResourcesPanelLayout);
        checkedOutResourcesPanelLayout.setHorizontalGroup(
            checkedOutResourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkedOutResourcesPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(checkedOutResourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkedOutResourcesPanelLayout.createSequentialGroup()
                        .addComponent(checkedOutBookButton)
                        .addGap(32, 32, 32)
                        .addComponent(checkedOutJournalButton)
                        .addGap(28, 28, 28)
                        .addComponent(checkedOutConfButton))
                    .addComponent(checkedOutPubLabel)
                    .addComponent(checkoutRoomLabel)
                    .addGroup(checkedOutResourcesPanelLayout.createSequentialGroup()
                        .addComponent(checkedoutStudyButton)
                        .addGap(26, 26, 26)
                        .addComponent(checkedOutConfRoom))
                    .addComponent(checkedOutCameraButton))
                .addContainerGap(567, Short.MAX_VALUE))
        );
        checkedOutResourcesPanelLayout.setVerticalGroup(
            checkedOutResourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkedOutResourcesPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(checkedOutPubLabel)
                .addGap(18, 18, 18)
                .addGroup(checkedOutResourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkedOutBookButton)
                    .addComponent(checkedOutJournalButton)
                    .addComponent(checkedOutConfButton))
                .addGap(45, 45, 45)
                .addComponent(checkoutRoomLabel)
                .addGap(18, 18, 18)
                .addGroup(checkedOutResourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkedoutStudyButton)
                    .addComponent(checkedOutConfRoom))
                .addGap(40, 40, 40)
                .addComponent(checkedOutCameraButton)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Checked out resources", checkedOutResourcesPanel);

        jLabel3.setText("Publication");

        jLabel4.setText("Rooms");

        jLabel5.setText("Camera");

        roomCheckoutButton.setText("Checkout");
        roomCheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomCheckoutButtonActionPerformed(evt);
            }
        });

        cameraCheckoutButton.setText("Checkout");
        cameraCheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cameraCheckoutButtonActionPerformed(evt);
            }
        });

        jListRequestRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListRequestRoomMousePressed(evt);
            }
        });
        requestResourceList.setViewportView(jListRequestRoom);

        jScrollPane3.setViewportView(jRequestResourceCamera);

        javax.swing.GroupLayout resReqPanelLayout = new javax.swing.GroupLayout(resReqPanel);
        resReqPanel.setLayout(resReqPanelLayout);
        resReqPanelLayout.setHorizontalGroup(
            resReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resReqPanelLayout.createSequentialGroup()
                .addGroup(resReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resReqPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(resReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollRequestPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requestResourceList, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resReqPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)))
                .addGroup(resReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomCheckoutButton)
                    .addComponent(cameraCheckoutButton))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        resReqPanelLayout.setVerticalGroup(
            resReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resReqPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollRequestPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGroup(resReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resReqPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(roomCheckoutButton))
                    .addGroup(resReqPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(requestResourceList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGroup(resReqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resReqPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(cameraCheckoutButton))
                    .addGroup(resReqPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Resource Request", resReqPanel);

        jLabel1.setText("Reminder");

        javax.swing.GroupLayout notifPanelLayout = new javax.swing.GroupLayout(notifPanel);
        notifPanel.setLayout(notifPanelLayout);
        notifPanelLayout.setHorizontalGroup(
            notifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notifPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPaneReminder)
        );
        notifPanelLayout.setVerticalGroup(
            notifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notifPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneReminder, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Notifications", notifPanel);

        balanceDueLabel.setText("Total Amount due");

        clearBalanceButton.setText("Clear");
        clearBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBalanceButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListAllBill);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Resource    :    Resource ID     :    Amount");

        javax.swing.GroupLayout balancePanelLayout = new javax.swing.GroupLayout(balancePanel);
        balancePanel.setLayout(balancePanelLayout);
        balancePanelLayout.setHorizontalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balancePanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(balancePanelLayout.createSequentialGroup()
                        .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearBalanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(balanceDueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountDueTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        balancePanelLayout.setVerticalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balancePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceDueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountDueTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clearBalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        jTabbedPane1.addTab("Balance", balancePanel);

        publicationButtonGroup.add(bookRadioButton);
        bookRadioButton.setText("Book");
        bookRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRadioButtonActionPerformed(evt);
            }
        });

        publicationLabel.setText("Publication");

        publicationButtonGroup.add(journalRadioButton);
        journalRadioButton.setText("Journal");
        journalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journalRadioButtonActionPerformed(evt);
            }
        });

        publicationButtonGroup.add(confRadioButton);
        confRadioButton.setText("Conference paper");
        confRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(192, 192, 192)
                            .addComponent(confRadioButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(bookRadioButton)
                            .addGap(45, 45, 45)
                            .addComponent(journalRadioButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(publicationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(publicationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookRadioButton)
                    .addComponent(journalRadioButton)
                    .addComponent(confRadioButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        cameraLabel.setText("Camera");

        cameraSearchButton.setText("Search");
        cameraSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cameraSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cameraSearchButton))
                    .addComponent(cameraLabel))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cameraLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cameraSearchButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        roomLabel.setText("Room");

        roomButtonGroup.add(studyRoomRadioButton);
        studyRoomRadioButton.setText("Study Room");
        studyRoomRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyRoomRadioButtonActionPerformed(evt);
            }
        });

        roomButtonGroup.add(confRoomRadioButton);
        confRoomRadioButton.setText("Conference room");
        confRoomRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confRoomRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(studyRoomRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(confRoomRadioButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(roomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studyRoomRadioButton)
                    .addComponent(confRoomRadioButton))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout publicationPanelLayout = new javax.swing.GroupLayout(publicationPanel);
        publicationPanel.setLayout(publicationPanelLayout);
        publicationPanelLayout.setHorizontalGroup(
            publicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicationPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(publicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(publicationPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(526, Short.MAX_VALUE))
                    .addGroup(publicationPanelLayout.createSequentialGroup()
                        .addGroup(publicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        publicationPanelLayout.setVerticalGroup(
            publicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicationPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Resources", publicationPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studyRoomRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyRoomRadioButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Study room button clicked");
        RoomDetails.roomType = "Study Room";
        new RoomReservationFrame().setVisible(true);
        
    }//GEN-LAST:event_studyRoomRadioButtonActionPerformed

    private void confRoomRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confRoomRadioButtonActionPerformed
        // TODO add your handling code here:
        RoomDetails.roomType = "Conference Room";
        new RoomReservationFrame().setVisible(true);
    }//GEN-LAST:event_confRoomRadioButtonActionPerformed

    private void cameraSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cameraSearchButtonActionPerformed
        
        new CameraFrame().setVisible(true);
        
    }//GEN-LAST:event_cameraSearchButtonActionPerformed

    private void confRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confRadioButtonActionPerformed
        // TODO add your handling code here:
        new ConferencePaperDetailsFrame().setVisible(true);
    }//GEN-LAST:event_confRadioButtonActionPerformed

    private void bookRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRadioButtonActionPerformed
        // go to BookDetailsFrame
        System.out.println("Book radio button clicked");
        new BookDetailsFrame().setVisible(true);
    }//GEN-LAST:event_bookRadioButtonActionPerformed

    private void journalRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journalRadioButtonActionPerformed
        // TODO add your handling code here:
        new JournalDetailsFrame().setVisible(true);
    }//GEN-LAST:event_journalRadioButtonActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

     // TODO add your handling code here:
        
        switch (jTabbedPane1.getSelectedIndex())
        {
            case 2: refreshResourceRequest();
            refreshResourceRequestRoom();
            refreshResourceRequestCamera();
            
            
                 break;
             case 3 : 
                 refreshNotifications();
                 break;
            case 4:
                
                refreshAmount();
                break;
                
           
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void clearBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBalanceButtonActionPerformed
        // TODO add your handling code here:
        
          int reply = JOptionPane.showConfirmDialog(null,"Clear Balance ? ", "Clear", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            
           DatabaseHelper.clearAmountDue(PatronDetails.getPid());
        }
        refreshAmount();
        //Clear List
        jListAllBill.setListData(new Object[0]);
        
        
        
    }//GEN-LAST:event_clearBalanceButtonActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseReleased

    private void saveChangesBtnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesBtnStudentActionPerformed

        try{
        
        StudentDetails.sNumber = sidTxtField.getText();
        StudentDetails.sDob = dobTxtField.getText();
        StudentDetails.sFname = fnameTxtField.getText();
        StudentDetails.sLname = lnameTxtField.getText();
        StudentDetails.sSex = sextxtField.getText();
        StudentDetails.sNationality = nationalityTxtField.getText();
        StudentDetails.sPhoneNo = Integer.parseInt(phoneNoTxtField.getText());
        StudentDetails.sAltPhoneNo = Integer.parseInt(altphoneNoTxtField.getText());
        //StudentDetails.sAddress = addressTxtField;
        StudentDetails.sDept = deptTxtField.getText();
        StudentDetails.sClassification = classificationTxtField.getText();
        StudentDetails.sCategory = categTxtField.getText();
        StudentDetails.sDegProg = degprogTxtField.getText();
        //JOptionPane.showMessageDialog(null, "Clicked on Student Save Button // call Insert procedure from Manish with the values");
        //JOptionPane.showMessageDialog(null, StudentDetails.sClassification);
        
        DatabaseHelper.updateStudent();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Enter in correct format");
        }
        
    }//GEN-LAST:event_saveChangesBtnStudentActionPerformed

    private void saveChangesBtnFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesBtnFacultyActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Clicked on Student Save Button // call Insert faculty procedure from Manish with the values");
        
        try{
        
        FacultyDetails.fFname = fFnameTxtField.getText();
        FacultyDetails.fLname = fLnameTxtField.getText();
        FacultyDetails.fNationality = fNationalityTxtField.getText();
        FacultyDetails.fDept = fDeptTxtField.getText();
        FacultyDetails.fCategory = fCategoryTxtField.getText();
        
        //JOptionPane.showMessageDialog(null, "Clicked on Student Save Button // call Insert procedure from Manish with the values");
        //JOptionPane.showMessageDialog(null, StudentDetails.sClassification);
        
        DatabaseHelper.updateFaculty();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Enter in correct format");
        }
        
        
    }//GEN-LAST:event_saveChangesBtnFacultyActionPerformed

    private void roomCheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomCheckoutButtonActionPerformed

        

// get room no and update checkout table
        
        if ( jListRequestRoom.isSelectionEmpty())
              JOptionPane.showMessageDialog(null, "Please Select Room to checkout");
        
        
         String roomNo = (String) jListRequestRoom.getSelectedValue();

        for(RoomDetails room : roomList){
            if(room.roomNo == roomNo){
                try {
                    rid = room.rid;
                    
                    DatabaseHelper.checkoutRoom(rid,PatronDetails.pid);
                     JOptionPane.showMessageDialog(null, "checkout Succcess");
                    
                    break;
                } catch (SQLException ex) {
                    Logger.getLogger(PatronDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "FailToCheckout"+ex.getMessage());
                }
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_roomCheckoutButtonActionPerformed

    private void cameraCheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cameraCheckoutButtonActionPerformed
        // TODO add your handling code here:
        
                
                 if ( jRequestResourceCamera.isSelectionEmpty())
              JOptionPane.showMessageDialog(null, "Please Select Camera to checkout");
        
        
         String camId = (String) jRequestResourceCamera.getSelectedValue();
        System.out.println("Camid"+camId);
         if(DatabaseHelper.isCameraAvailable(PatronDetails.getPid()))
         {
        for(CameraDetails camera : cameraList){
            if(camera.camId == camId){
                try {
                    
                    rid = camera.rid;
                    System.out.println("Printing rid"+rid);
                    DatabaseHelper.checkoutCamera(rid,PatronDetails.pid);
                                         JOptionPane.showMessageDialog(null, "checkout Succcess");
                                         //sad
                                          refreshResourceRequestCamera();
                    break;
                } catch (SQLException ex) {
                    Logger.getLogger(PatronDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "FailToCheckout"+ex.getMessage());
                }
            }
        
        }
    }
         else
             JOptionPane.showMessageDialog(null, "Cannot Checkout since no confirmation ");
    }//GEN-LAST:event_cameraCheckoutButtonActionPerformed

    private void checkedOutBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedOutBookButtonActionPerformed
        new CheckedoutBookDetailsFrame().setVisible(true);
    }//GEN-LAST:event_checkedOutBookButtonActionPerformed

    private void checkedOutJournalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedOutJournalButtonActionPerformed
        // TODO add your handling code here:
        new CheckedoutJournalDetailsFrame().setVisible(true);
    }//GEN-LAST:event_checkedOutJournalButtonActionPerformed

    private void checkedOutConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedOutConfButtonActionPerformed
        // TODO add your handling code here:
        new CheckedoutConfProceedingFrame().setVisible(true);
    }//GEN-LAST:event_checkedOutConfButtonActionPerformed

    private void checkedoutStudyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedoutStudyButtonActionPerformed
        // TODO add your handling code here:
        new CheckedoutRoom("Study Room").setVisible(true);
    }//GEN-LAST:event_checkedoutStudyButtonActionPerformed

    private void checkedOutConfRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedOutConfRoomActionPerformed
        // TODO add your handling code here:
        new CheckedoutRoom("Conference Room").setVisible(true);
    }//GEN-LAST:event_checkedOutConfRoomActionPerformed

    private void checkedOutCameraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedOutCameraButtonActionPerformed
        new CheckedoutCamera().setVisible(true);
    }//GEN-LAST:event_checkedOutCameraButtonActionPerformed

    private void jListRequestRoomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListRequestRoomMousePressed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jListRequestRoomMousePressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatronDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatronDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatronDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatronDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PatronDetailsFrame().setVisible(true);
                
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(PatronDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextArea addressTxtField;
    private javax.swing.JLabel altPhoneNoLabel;
    private javax.swing.JTextField altphoneNoTxtField;
    private javax.swing.JTextField amountDueTxtField;
    private javax.swing.JLabel balanceDueLabel;
    private javax.swing.JPanel balancePanel;
    private javax.swing.JRadioButton bookRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cameraCheckoutButton;
    private javax.swing.JLabel cameraLabel;
    private javax.swing.JButton cameraSearchButton;
    private javax.swing.JTextField categTxtField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JRadioButton checkedOutBookButton;
    private javax.swing.JRadioButton checkedOutCameraButton;
    private javax.swing.JRadioButton checkedOutConfButton;
    private javax.swing.JRadioButton checkedOutConfRoom;
    private javax.swing.JRadioButton checkedOutJournalButton;
    private javax.swing.JLabel checkedOutPubLabel;
    private javax.swing.JPanel checkedOutResourcesPanel;
    private javax.swing.JRadioButton checkedoutStudyButton;
    private javax.swing.JLabel checkoutRoomLabel;
    private javax.swing.JLabel classificationLabel;
    private javax.swing.JTextField classificationTxtField;
    private javax.swing.JButton clearBalanceButton;
    private javax.swing.JRadioButton confRadioButton;
    private javax.swing.JRadioButton confRoomRadioButton;
    private javax.swing.JLabel degProgLabel;
    private javax.swing.JTextField degprogTxtField;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JTextField deptTxtField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTxtField;
    private javax.swing.JTextField fCategoryTxtField;
    private javax.swing.JLabel fCtegoryLabel;
    private javax.swing.JLabel fDeptLabel;
    private javax.swing.JTextField fDeptTxtField;
    private javax.swing.JLabel fFnameLabel;
    private javax.swing.JTextField fFnameTxtField;
    private javax.swing.JLabel fLnameLabel;
    private javax.swing.JTextField fLnameTxtField;
    private javax.swing.JLabel fNationalityLabel;
    private javax.swing.JTextField fNationalityTxtField;
    private javax.swing.JLabel fNumberLabel;
    private javax.swing.JTextField fNumberTxtField;
    private javax.swing.JPanel facultyPanel;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jListAllBill;
    private javax.swing.JList jListRequestRoom;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JList jRequestResourceCamera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneReminder;
    private javax.swing.JScrollPane jScrollRequestPublication;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton journalRadioButton;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameTxtField;
    private javax.swing.JLabel nationalityLabel;
    private javax.swing.JTextField nationalityTxtField;
    private javax.swing.JPanel notifPanel;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JTextField phoneNoTxtField;
    private javax.swing.JPanel profilePanel;
    private javax.swing.ButtonGroup publicationButtonGroup;
    private javax.swing.JLabel publicationLabel;
    private javax.swing.JPanel publicationPanel;
    private javax.swing.JScrollPane requestResourceList;
    private javax.swing.JPanel resReqPanel;
    private javax.swing.ButtonGroup roomButtonGroup;
    private javax.swing.JButton roomCheckoutButton;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JButton saveChangesBtnFaculty;
    private javax.swing.JButton saveChangesBtnStudent;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JTextField sextxtField;
    private javax.swing.JTextField sidTxtField;
    private javax.swing.JLabel studentIdLabel;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JRadioButton studyRoomRadioButton;
    // End of variables declaration//GEN-END:variables

    private void refreshAmount() {
        
        try {
            populateBillList();
            
            String pay=DatabaseHelper.getAmountDue(PatronDetails.getPid());
            amountDueTxtField.setText(pay)
                    
               ;
            System.out.println(PatronDetails.getPid()+" pays " + pay);
        } catch (SQLException ex) {
            Logger.getLogger(PatronDetailsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void refreshNotifications() {
       
        JList list=DatabaseHelper.getNotification(PatronDetails.getPid());
        
        jScrollPaneReminder.setViewportView(list);
        
     /*  System.out.println("list is added to scrollpane");
       
        for (int i = 0; i < list.getModel().getSize(); i++) {
            Object item = list.getModel().getElementAt(i);
            System.out.println("Item = " + item);
        }
       
        
        JScrollPane jScrollPaneNotifications = new JScrollPane(list);
        
        */
    }

    private void displayStudentDetails() {
        sidTxtField.setText(StudentDetails.sNumber);
        dobTxtField.setText(StudentDetails.sDob);
        fnameTxtField.setText(StudentDetails.sFname);
        lnameTxtField.setText(StudentDetails.sLname);
        sextxtField.setText(StudentDetails.sSex);
        nationalityTxtField.setText(StudentDetails.sNationality);
        phoneNoTxtField.setText(String.valueOf(StudentDetails.sPhoneNo));
        altphoneNoTxtField.setText(String.valueOf(StudentDetails.sAltPhoneNo));
        addressTxtField.append(StudentDetails.sAddress);
        deptTxtField.setText(StudentDetails.sDept);
        classificationTxtField.setText(StudentDetails.sClassification);
        categTxtField.setText(StudentDetails.sCategory);
        degprogTxtField.setText(StudentDetails.sDegProg);
    }

    private void refreshResourceRequest() {

        JList list=DatabaseHelper.getRequestedPublication(PatronDetails.getPid());
        jScrollRequestPublication.setViewportView(list);
    }
    
    private void refreshResourceRequestRoom() {
        
        DefaultListModel dlm = new DefaultListModel();
        roomList=DatabaseHelper.getRequestedRooms(PatronDetails.getPid());
        
        for(int i=0; i< roomList.size(); i++)
        {
            RoomDetails room = roomList.get(i);
            dlm.addElement(room.roomNo);
            //dlm.addElement(room.roomNo + " : "+room.checkoutDate+" : "+room.dueDate);
            
           
            
            //System.out.println(book.bTitle);
        }
        jListRequestRoom.setModel(dlm);
        //testing
        System.out.println("in func populate resource request room list");
        
        
    }
      private void refreshResourceRequestCamera() {

       
        DefaultListModel dlm = new DefaultListModel();
          cameraList=DatabaseHelper.getRequestedCameras(PatronDetails.getPid());
        
        
        for(int i=0; i< cameraList.size(); i++)
        {
            CameraDetails cam = cameraList.get(i);
            dlm.addElement(cam.camId);
            
           
            
            //System.out.println(book.bTitle);
        }
        jRequestResourceCamera.setModel(dlm);
        //testing
        System.out.println("in func populate camera request room list");
        
        
    }

    private void displayFacultyDetails() {
        fNumberTxtField.setText(FacultyDetails.fNumber);
        fFnameTxtField.setText(FacultyDetails.fFname);
        fLnameTxtField.setText(FacultyDetails.fLname);
        fDeptTxtField.setText(FacultyDetails.fDept);
        fNationalityTxtField.setText(FacultyDetails.fNationality);
        fCategoryTxtField.setText(FacultyDetails.fCategory);
    }
    
    
}
