
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author amol
 */
public class RoomReservationFrame extends javax.swing.JFrame {

    /**
     * Creates new form RoomSelectFrame
     */
    
    ArrayList<RoomDetails> roomList;
    String libName = "";
    int rid;
    public RoomReservationFrame() {
        initComponents();
       
        if(RoomDetails.roomType == "conference")
        {
            hillRadioButton.setVisible(false);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libsButtonGroup = new javax.swing.ButtonGroup();
        roomCapacityLabel = new javax.swing.JLabel();
        libnameLabel = new javax.swing.JLabel();
        capacityTxtField = new javax.swing.JTextField();
        hillRadioButton = new javax.swing.JRadioButton();
        huntRadioButton = new javax.swing.JRadioButton();
        roomSearchButton = new javax.swing.JButton();
        roomReserveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRoomList = new javax.swing.JList();
        enterDateLabel = new javax.swing.JLabel();
        startTimeLabel = new javax.swing.JLabel();
        roomStartTimeComboBox = new javax.swing.JComboBox();
        endTimeLabel = new javax.swing.JLabel();
        roomEndTimeComboBox = new javax.swing.JComboBox();
        startDateTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        endDateTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roomCapacityLabel.setText("Capacity");

        libnameLabel.setText("Library");

        capacityTxtField.setText("4");

        libsButtonGroup.add(hillRadioButton);
        hillRadioButton.setText("D.H.Hill");
        hillRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hillRadioButtonActionPerformed(evt);
            }
        });

        libsButtonGroup.add(huntRadioButton);
        huntRadioButton.setText("J.B. Hunt");
        huntRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huntRadioButtonActionPerformed(evt);
            }
        });

        roomSearchButton.setText("Search");
        roomSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomSearchButtonActionPerformed(evt);
            }
        });

        roomReserveButton.setText("Reserve");
        roomReserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomReserveButtonActionPerformed(evt);
            }
        });

        jRoomList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRoomListMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jRoomList);

        enterDateLabel.setText("Start date");

        startTimeLabel.setText("Start time");

        roomStartTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1:00", "1:30", "2:00", "2:30", "3:00", "3:30", "4:00", "4:30", "5:00", "5:30", "6:00", "6:30", "7:00", "7:30", "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "24:00" }));

        endTimeLabel.setText("End time");

        roomEndTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1:00", "1:30", "2:00", "2:30", "3:00", "3:30", "4:00", "4:30", "5:00", "5:30", "6:00", "6:30", "7:00", "7:30", "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "24:00" }));
        roomEndTimeComboBox.setSelectedIndex(2);
        roomEndTimeComboBox.setToolTipText("");

        startDateTxtField.setText("2015/11/13");
        startDateTxtField.setToolTipText("");

        jLabel1.setText("End date");

        endDateTxtField.setText("2015/11/13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(hillRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(huntRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(roomSearchButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(startTimeLabel)
                                        .addGap(12, 12, 12)
                                        .addComponent(roomStartTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enterDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(startDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(endDateTxtField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(endTimeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(roomEndTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 229, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roomCapacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)
                                .addComponent(libnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(243, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(roomReserveButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomCapacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hillRadioButton)
                    .addComponent(huntRadioButton)
                    .addComponent(capacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(endDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeLabel)
                    .addComponent(roomStartTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endTimeLabel)
                    .addComponent(roomEndTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(roomSearchButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomReserveButton)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomReserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomReserveButtonActionPerformed
        // unpdate room checkout table
        // update resource request
        String str = (String)(jRoomList.getSelectedValue());
        String roomNo = str.split(",")[0].trim();
        String enteredStartDate = startDateTxtField.getText() + " " + roomStartTimeComboBox.getSelectedItem().toString();
        String enteredEndDate = endDateTxtField.getText() + " " + roomEndTimeComboBox.getSelectedItem().toString();
        //JOptionPane.showMessageDialog(null, roomNo + " " + enteredStartDate + " " + enteredEndDate);
        DatabaseHelper.reserveRoom(roomNo, PatronDetails.pid, enteredStartDate, enteredEndDate);
        
        
    }//GEN-LAST:event_roomReserveButtonActionPerformed

    private void roomSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomSearchButtonActionPerformed
        // TODO add your handling code here:
        if(capacityTxtField.getText() == "")
            JOptionPane.showMessageDialog(null, "Enter capacity");
        else if(!hillRadioButton.isSelected() && !huntRadioButton.isSelected() ) {
            JOptionPane.showMessageDialog(null, "Select libary name");
        }
        else
        {
            populateRoomList();
        }
        
    }//GEN-LAST:event_roomSearchButtonActionPerformed

    private void huntRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huntRadioButtonActionPerformed
        libName = "J. B. Hunt";
        
    }//GEN-LAST:event_huntRadioButtonActionPerformed

    private void hillRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hillRadioButtonActionPerformed
        libName = "D. H. Hill";
    }//GEN-LAST:event_hillRadioButtonActionPerformed

    private void jRoomListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRoomListMouseReleased
       
       
    }//GEN-LAST:event_jRoomListMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomReservationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacityTxtField;
    private javax.swing.JTextField endDateTxtField;
    private javax.swing.JLabel endTimeLabel;
    private javax.swing.JLabel enterDateLabel;
    private javax.swing.JRadioButton hillRadioButton;
    private javax.swing.JRadioButton huntRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jRoomList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel libnameLabel;
    private javax.swing.ButtonGroup libsButtonGroup;
    private javax.swing.JLabel roomCapacityLabel;
    private javax.swing.JComboBox roomEndTimeComboBox;
    private javax.swing.JButton roomReserveButton;
    private javax.swing.JButton roomSearchButton;
    private javax.swing.JComboBox roomStartTimeComboBox;
    private javax.swing.JTextField startDateTxtField;
    private javax.swing.JLabel startTimeLabel;
    // End of variables declaration//GEN-END:variables

    private void populateRoomList() {
        
        DefaultListModel dlm = new DefaultListModel();
        //JOptionPane.showMessageDialog(null, "populate room list");
        roomList = DatabaseHelper.getRooms(Integer.parseInt(capacityTxtField.getText()), roomStartTimeComboBox.getSelectedItem().toString(), roomEndTimeComboBox.getSelectedItem().toString(), startDateTxtField.getText(), endDateTxtField.getText(),libName);
        for(int i=0; i< roomList.size(); i++)
        {
            RoomDetails room = roomList.get(i);
            dlm.addElement(room.roomNo + " , " + room.position);
            System.out.println(room.roomNo + " , " + room.position);
            
        }
        jRoomList.setModel(dlm);
    }
}
